[theme]
primaryColor = "#FF6B6B"  # Vibrant Coral Red
backgroundColor = "#F8F9FA"  # Soft Light Gray
secondaryBackgroundColor = "#E9ECEF"  # Slightly Darker Gray
textColor = "#212529"  # Deep Charcoal
font = "sans serif"
